### PR TITLE
changed the scaling of the acceleration values. 

### PR DESCRIPTION
**Pull request by keroe**
Probably a copy-paste mistake

### CODE REVIEW

**Comment by RomanRobotnik** [comment]
Hi,
Why are you multiplying by 9.81? In the current version it's being converted from degrees/sec to rads/sec.

**Comment by marbosjo** [comment]
Acceleration is normally measured in m/s^2...

Maybe vmu931 is publishing data in g (=9.81), so this os way is multiplied by this value.

  the docs does not say which units are used, but images are shown in m/s^2

**Comment by RomanRobotnik** [comment]
That's true... I need to sleep a bit more.... Merging then

**Comment by keroe** [comment]
I tested it with gravity, so output should be g. The mistake could also be in the scaling, because there degrees/sec doesn't make sense either, but I did not test that.

**Pull request merged**
